// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZW.MyAirport.EF;

namespace ZW.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    [Migration("20200221155607_ForeignKeyFLight4")]
    partial class ForeignKeyFLight4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZW.MyAirport.EF.Flight", b =>
                {
                    b.Property<int>("FLIGHTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CIE")
                        .HasColumnType("int");

                    b.Property<string>("DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DHC")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JEX")
                        .HasColumnType("int");

                    b.Property<string>("LIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("PKG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FLIGHTID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("ZW.MyAirport.EF.Luggage", b =>
                {
                    b.Property<int>("LUGGAGEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE_IATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_CREATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESTINATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESCALE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FLIGHTID")
                        .HasColumnType("int");

                    b.Property<bool>("PRIORITAIRE")
                        .HasColumnType("bit");

                    b.Property<string>("SSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LUGGAGEID");

                    b.ToTable("Luggages");
                });
#pragma warning restore 612, 618
        }
    }
}
